# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include(ExternalProject)
include(${LITERTLM_TFLITE_PACKAGE_DIR}/tflite_config.cmake)

setup_external_install_structure("${LITERTLM_TFLITE_INSTALL_PREFIX}")

set(LITERTLM_TFLITE_TAG "master" CACHE STRING "TFLite git tag")

if(NOT EXISTS "${LITERTLM_LITERTLM_TFLITE_STATIC_LIB}")
    message(STATUS "TFLite not found. Configuring external build...")

    ExternalProject_Add(
        tflite_external
        DEPENDS
            absl_external
            flatbuffers_external
            gtest_external
            opencl_headers_external
            protobuf_external
            sentencepiece_external
        GIT_REPOSITORY  https://github.com/tensorflow/tensorflow.git
        GIT_TAG         ${LITERTLM_TFLITE_TAG}
        PREFIX          "${LITERTLM_TFLITE_EXT_PREFIX}"
        SOURCE_SUBDIR   "tensorflow/lite"
        UPDATE_COMMAND
            git fetch origin ${LITERTLM_TFLITE_TAG}
            COMMAND git reset --hard FETCH_HEAD
            COMMAND git clean -dfx
        PATCH_COMMAND
            ${CMAKE_COMMAND}
            "-DLITERTLM_ORCHESTRATION_PHASE=${LITERTLM_ORCHESTRATION_PHASE}"
            "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
            "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
            "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
            "-DLITERTLM_PROJECT_ROOT=${LITERTLM_PROJECT_ROOT}"
            "-DLITERTLM_TFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}"
            "-DLITERTLM_TFLITE_CONFIG_PATH=${LITERTLM_TFLITE_CONFIG_PATH}"
            "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
            "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
            "-DLITERTLM_FLATBUFFERS_PACKAGE_DIR=${LITERTLM_FLATBUFFERS_PACKAGE_DIR}"
            "-DLITERTLM_FLATBUFFERS_CONFIG_PATH=${LITERTLM_FLATBUFFERS_CONFIG_PATH}"
            "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
            "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
            "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
            "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"
            "-DLITERTLM_TFLITE_SRC_DIR=${LITERTLM_TFLITE_SRC_DIR}"
            "-DLITERTLM_TFLITE_BUILD_DIR=${LITERTLM_TFLITE_BUILD_DIR}"
            "-DLITERTLM_TFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}"
            "-DLITERTLM_TENSORFLOW_SRC_DIR=${LITERTLM_TENSORFLOW_SRC_DIR}"
            "-DLITERTLM_FLATC_EXECUTABLE=${LITERTLM_FLATC_EXECUTABLE}"
            "-DLITERTLM_PATCHES_DIR=${LITERTLM_PATCHES_DIR}"
            -P "${LITERTLM_CMAKE_PACKAGES_DIR}/tflite/tflite_patcher.cmake"
        CMAKE_ARGS
            ${LITERTLM_TOOLCHAIN_FILE}
            ${LITERTLM_TOOLCHAIN_ARGS}
            "-DLITERTLM_ORCHESTRATION_PHASE=${LITERTLM_ORCHESTRATION_PHASE}"
            "-DLITERTLM_BIN_EXT=${LITERTLM_BIN_EXT}"
            "-DLITERTLM_STATIC_LIB_EXT=${LITERTLM_STATIC_LIB_EXT}"
            "-DLITERTLM_DYN_LIB_EXT=${LITERTLM_DYN_LIB_EXT}"
            "-DLITERTLM_LIB_PREFIX=${LITERTLM_LIB_PREFIX}"
            "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
            "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
            "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
            "-DLITERTLM_TARGET_MAP_DIR=${LITERTLM_TARGET_MAP_DIR}"
            "-DLITERTLM_PROJECT_ROOT=${LITERTLM_PROJECT_ROOT}"
            "-DLITERTLM_TFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}"
            "-DLITERTLM_TFLITE_CONFIG_PATH=${LITERTLM_TFLITE_CONFIG_PATH}"
            "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
            "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
            "-DLITERTLM_FLATBUFFERS_PACKAGE_DIR=${LITERTLM_FLATBUFFERS_PACKAGE_DIR}"
            "-DLITERTLM_FLATBUFFERS_CONFIG_PATH=${LITERTLM_FLATBUFFERS_CONFIG_PATH}"
            "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
            "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
            "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
            "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"
            "-DCMAKE_INSTALL_PREFIX=${LITERTLM_TFLITE_INSTALL_PREFIX}"
            "-DCMAKE_INSTALL_LIBDIR=lib"
            "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
            "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
            "-DCMAKE_POLICY_DEFAULT_CMP0169=OLD"
            "-DCMAKE_POLICY_DEFAULT_CMP0170=OLD"
            "-DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}"
            "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}"
            "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
            "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
            "-DPNG_FOUND=ON"
            "-DPNG_LIBRARY=${libpng_lib_BINARY_DIR}/libpng.a"
            "-DPNG_PNG_INCLUDE_DIR=${libpng_lib_SOURCE_DIR}"
            "-DTFLITE_ENABLE_INSTALL=OFF"
            "-DTFLITE_ENABLE_XNNPACK=ON"
            "-DTFLITE_ENABLE_RESOURCE_VARIABLE=OFF"
            "-DXNNPACK_SET_VERBOSITY=OFF"
            "-DTFLITE_ENABLE_GPU=OFF"
            "-DTFLITE_HOST_TOOLS_DIR=${FLATBUFFERS_BIN_DIR}"
            "-DTFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}"
            "-DLITERTLM_PROJECT_ROOT=${LITERTLM_PROJECT_ROOT}"
            "-DLITERTLM_ABSL_LIBRARIES=${LITERTLM_ABSL_LIBS_FLAT}"
            "-DLITERTLM_PROTOBUF_LIBRARIES=${LITERTLM_PROTOBUF_LIBS_FLAT}"
            "-DLITERTLM_PROTOBUF_INCLUDE_DIRS=${LITERTLM_PROTOBUF_INCLUDE_DIR}"
            "-DLITERTLM_PROTOC_EXECUTABLE=${LITERTLM_HOST_PROTOC}"
            "-DLITERTLM_TFLITE_SRC_DIR=${LITERTLM_TFLITE_SRC_DIR}"
            "-DLITERTLM_TFLITE_BUILD_DIR=${LITERTLM_TFLITE_BUILD_DIR}"
            "-DLITERTLM_TFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}"
            "-DLITERTLM_TENSORFLOW_SRC_DIR=${LITERTLM_TENSORFLOW_SRC_DIR}"
            "-DLITERTLM_FLATC_EXECUTABLE=${LITERTLM_FLATC_EXECUTABLE}"
            "-DLITERTLM_PATCHES_DIR=${LITERTLM_PATCHES_DIR}"
    )
    block()
        set(LITERTLM_GENERATE_TARGET_MAP OFF CACHE BOOL "Disable target map generation for TFLite external project" FORCE)
        if(LITERTLM_GENERATE_TARGET_MAP)
            ExternalProject_Add_Step(tflite_external generate_target_map
                COMMAND ${CMAKE_COMMAND}
                    "-DDEP_NAME=tflite"
                    "-DSEARCH_DIR=${LITERTLM_TFLITE_BUILD_DIR}"
                    "-DSEARCH_STR=LITERTLM_TFLITE_BUILD_DIR"
                    "-DOUTPUT_FILE=${LITERTLM_TFLITE_TARGET_MAP_PATH}"
                    -P ${LITERTLM_SCRIPTS_DIR}/generate_target_map.cmake
                DEPENDEES install
                BYPRODUCTS ${LITERTLM_TFLITE_TARGET_MAP_PATH}
            )
        endif()
    endblock()
endif()

if(NOT TARGET tflite_external)
    add_custom_target(tflite_external)
endif()

include(${LITERTLM_TFLITE_AGGREGATE_PATH})
generate_tflite_aggregate()
