# --- Autogenerated target map for re2
# To preserve manual edits, set LITERTLM_GENERATE_TARGET_MAP=OFF

set(LITERTLM_RE2_TARGET_MAP
    "re2::re2=${LITERTLM_RE2_LIB_DIR}/libre2${CMAKE_STATIC_LIBRARY_SUFFIX}"
    CACHE INTERNAL "Mapping of re2 targets"
)
