# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include(ExternalProject)
include("${LITERTLM_TOKENIZERS_PACKAGE_DIR}/tokenizers_config.cmake")

set(LITERTLM_TOKENIZERS_TAG "c586c52f93f7b060753bd2388eb96a105cb7374d"
  CACHE STRING "Tokenizers-cpp git tag")

message(STATUS "tokenizers-cpp not found. Configuring external build...")
ExternalProject_Add(
  tokenizers-cpp_external
  DEPENDS
    absl_external
    protobuf_external
    gtest_external
    sentencepiece_external
  GIT_REPOSITORY
    https://github.com/mlc-ai/tokenizers-cpp
  GIT_TAG
    ${LITERTLM_TOKENIZERS_TAG}
  PREFIX
    ${LITERTLM_TOKENIZERS_EXT_PREFIX}
  UPDATE_COMMAND
    git fetch origin ${LITERTLM_TOKENIZERS_TAG}
    COMMAND git reset --hard FETCH_HEAD
    COMMAND git clean -dfx
  PATCH_COMMAND
    ${CMAKE_COMMAND}
    "-DLITERTLM_ORCHESTRATION_PHASE=${LITERTLM_ORCHESTRATION_PHASE}"
    "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
    "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
    "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
    "-DLITERTLM_PROJECT_ROOT=${LITERTLM_PROJECT_ROOT}"
    "-DLITERTLM_TOKENIZERS_PACKAGE_DIR=${LITERTLM_TOKENIZERS_PACKAGE_DIR}"
    "-DLITERTLM_TOKENIZERS_CONFIG_PATH=${LITERTLM_TOKENIZERS_CONFIG_PATH}"
    "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
    "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
    "-DLITERTLM_FLATBUFFERS_PACKAGE_DIR=${LITERTLM_FLATBUFFERS_PACKAGE_DIR}"
    "-DLITERTLM_FLATBUFFERS_CONFIG_PATH=${LITERTLM_FLATBUFFERS_CONFIG_PATH}"
    "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
    "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
    "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
    "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"
    "-DLITERTLM_SENTENCEPIECE_SRC_DIR=${LITERTLM_SENTENCEPIECE_SRC_DIR}"
    "-DLITERTLM_SENTENCEPIECE_CONFIG_PATH=${LITERTLM_SENTENCEPIECE_CONFIG_PATH}"
    "-DLITERTLM_SENTENCEPIECE_BUILD_DIR=${LITERTLM_SENTENCEPIECE_BUILD_DIR}"
    "-DLITERTLM_SENTENCEPIECE_PACKAGE_DIR=${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}"
    "-DLITERTLM_TENSORFLOW_SRC_DIR=${LITERTLM_TENSORFLOW_SRC_DIR}"
    "-DLITERTLM_FLATC_EXECUTABLE=${LITERTLM_FLATC_EXECUTABLE}"
    "-DLITERTLM_PATCHES_DIR=${LITERTLM_PATCHES_DIR}"
    -P "${LITERTLM_CMAKE_PACKAGES_DIR}/tokenizers/tokenizers_patcher.cmake"
  CMAKE_ARGS
    ${LITERTLM_TOOLCHAIN_FILE}
    ${LITERTLM_TOOLCHAIN_ARGS}
    "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
    "-DCMAKE_INSTALL_PREFIX=${LITERTLM_TOKENIZERS_INSTALL_PREFIX}"
    "-DCMAKE_INSTALL_LIBDIR=lib"
    "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
    "-DCMAKE_POLICY_DEFAULT_CMP0169=OLD"
    "-DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}"
    "-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -include cstdint"
    "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}"
    "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
    "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
    "-DLITERTLM_ORCHESTRATION_PHASE=${LITERTLM_ORCHESTRATION_PHASE}"
    "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
    "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
    "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
    "-DLITERTLM_PROJECT_ROOT=${LITERTLM_PROJECT_ROOT}"
    "-DLITERTLM_TOKENIZERS_PACKAGE_DIR=${LITERTLM_TOKENIZERS_PACKAGE_DIR}"
    "-DLITERTLM_TOKENIZERS_CONFIG_PATH=${LITERTLM_TOKENIZERS_CONFIG_PATH}"
    "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
    "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
    "-DLITERTLM_FLATBUFFERS_PACKAGE_DIR=${LITERTLM_FLATBUFFERS_PACKAGE_DIR}"
    "-DLITERTLM_FLATBUFFERS_CONFIG_PATH=${LITERTLM_FLATBUFFERS_CONFIG_PATH}"
    "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
    "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
    "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
    "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"
    "-DLITERTLM_SENTENCEPIECE_SRC_DIR=${LITERTLM_SENTENCEPIECE_SRC_DIR}"
    "-DLITERTLM_SENTENCEPIECE_BUILD_DIR=${LITERTLM_SENTENCEPIECE_BUILD_DIR}"
    "-DLITERTLM_SENTENCEPIECE_PACKAGE_DIR=${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}"
    "-DLITERTLM_SENTENCEPIECE_CONFIG_PATH=${LITERTLM_SENTENCEPIECE_CONFIG_PATH}"
    "-DLITERTLM_FLATC_EXECUTABLE=${LITERTLM_FLATC_EXECUTABLE}"
    "-DLITERTLM_PATCHES_DIR=${LITERTLM_PATCHES_DIR}"
    "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"


)

# Do not generate target map for tokenizers-cpp.
# This project builds internal projects that have not been disabled.

#--- Legacy target map generation for tokenizers-cpp. This is not recommended and may be removed in future versions.
import_static_lib(imp_tokenizers_c
  "${LITERTLM_TOKENIZERS_BUILD_DIR}/libtokenizers_c.a")
import_static_lib(imp_tokenizers_cpp
  "${LITERTLM_TOKENIZERS_BUILD_DIR}/libtokenizers_cpp.a")

add_library(tokenizers_libs INTERFACE)
target_include_directories(tokenizers_libs INTERFACE ${LITERTLM_TOKENIZERS_INCLUDE_DIR})

target_link_libraries(tokenizers_libs INTERFACE
  imp_tokenizers_c
  imp_tokenizers_cpp
)

if(NOT TARGET LiteRTLM::tokenizers::tokenizers)
    add_library(LiteRTLM::tokenizers::tokenizers INTERFACE IMPORTED GLOBAL)
    target_link_libraries(LiteRTLM::tokenizers::tokenizers INTERFACE tokenizers_libs)
endif()

set(_tokenizers_lib_paths
  "${LITERTLM_TOKENIZERS_BUILD_DIR}/libtokenizers_c.a"
  "${LITERTLM_TOKENIZERS_BUILD_DIR}/libtokenizers_cpp.a"
)
#---