# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set(PKG_ROOT ${CMAKE_CURRENT_SOURCE_DIR})
set(LITERTLM_TOKENIZERS_EXT_PREFIX ${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}/tokenizers-cpp CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_SRC_DIR ${LITERTLM_TOKENIZERS_EXT_PREFIX}/src/tokenizers-cpp_external CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_SRC_SENTENCEPIECE_DIR ${LITERTLM_TOKENIZERS_SRC_DIR}/sentencepiece CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_SRC_INCLUDE_DIR ${LITERTLM_TOKENIZERS_SRC_DIR}/include CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_SRC_WEB_DIR ${LITERTLM_TOKENIZERS_SRC_DIR}/web/src CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_BUILD_DIR ${LITERTLM_TOKENIZERS_EXT_PREFIX}/src/tokenizers-cpp_external-build CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_INSTALL_PREFIX ${LITERTLM_TOKENIZERS_EXT_PREFIX}/install CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_INCLUDE_DIR
  "${LITERTLM_TOKENIZERS_INSTALL_PREFIX}/include"
  "${LITERTLM_TOKENIZERS_SRC_DIR}"
  "${LITERTLM_TOKENIZERS_SRC_INCLUDE_DIR}"
  "${LITERTLM_TOKENIZERS_SRC_WEB_DIR}"
  "${LITERTLM_TOKENIZERS_SRC_SENTENCEPIECE_DIR}"
  "${LITERTLM_TOKENIZERS_SRC_SENTENCEPIECE_DIR}/src"
 CACHE INTERNAL "")
set(LITERTLM_TOKENIZERS_LIB_CHECK "${LITERTLM_TOKENIZERS_BUILD_DIR}/libtokenizers_cpp.a")
set(LITERTLM_TOKENIZERS_CMAKE_PATH "${LITERTLM_CMAKE_PACKAGES_DIR}/tokenizers/tokenizers.cmake" CACHE PATH "")
set(LITERTLM_TOKENIZERS_TARGET_MAP_PATH
  "${LITERTLM_TOKENIZERS_PACKAGE_DIR}/tokenizers_${LITERTLM_ORCHESTRATION_PHASE}_target_map.cmake"
  CACHE PATH "")
set(LITERTLM_TOKENIZERS_CONFIG_PATH "${LITERTLM_TOKENIZERS_PACKAGE_DIR}/tokenizers_config.cmake" CACHE PATH "")