# --- Autogenerated target map for tokenizers-cpp
# To preserve manual edits, set LITERTLM_GENERATE_TARGET_MAP=OFF

set(LITERTLM_TOKENIZERS-CPP_TARGET_MAP
    "tokenizers-cpp::tokenizers_c=${LITERTLM_TOKENIZERS_BUILD_DIR}/libtokenizers_c.a"
    "tokenizers-cpp::tokenizers_cpp=${LITERTLM_TOKENIZERS_BUILD_DIR}/libtokenizers_cpp.a"
    CACHE INTERNAL "Mapping of tokenizers-cpp targets"
)
