# --- Autogenerated target map for sentencepiece
# To preserve manual edits, set LITERTLM_GENERATE_TARGET_MAP=OFF

set(LITERTLM_SENTENCEPIECE_TARGET_MAP
    "sentencepiece::sentencepiece=${LITERTLM_SENTENCEPIECE_LIB_DIR}/libsentencepiece${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "sentencepiece::sentencepiece_train=${LITERTLM_SENTENCEPIECE_LIB_DIR}/libsentencepiece_train${CMAKE_STATIC_LIBRARY_SUFFIX}"
    CACHE INTERNAL "Mapping of sentencepiece targets"
)
