# --- Autogenerated target map for gtest
# To preserve manual edits, set LITERTLM_GENERATE_TARGET_MAP=OFF

set(LITERTLM_GTEST_TARGET_MAP
    "gtest::gmock=${LITERTLM_GTEST_LIB_DIR}/libgmock${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "gtest::gmock_main=${LITERTLM_GTEST_LIB_DIR}/libgmock_main${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "gtest::gtest=${LITERTLM_GTEST_LIB_DIR}/libgtest${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "gtest::gtest_main=${LITERTLM_GTEST_LIB_DIR}/libgtest_main${CMAKE_STATIC_LIBRARY_SUFFIX}"
    CACHE INTERNAL "Mapping of gtest targets"
)
