# --- Autogenerated target map for protobuf
# To preserve manual edits, set LITERTLM_GENERATE_TARGET_MAP=OFF

set(LITERTLM_PROTOBUF_TARGET_MAP
    "protobuf::protobuf-lite=${LITERTLM_PROTOBUF_LIB_DIR}/libprotobuf-lite${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "protobuf::protobuf=${LITERTLM_PROTOBUF_LIB_DIR}/libprotobuf${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "protobuf::protoc=${LITERTLM_PROTOBUF_LIB_DIR}/libprotoc${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "protobuf::upb=${LITERTLM_PROTOBUF_LIB_DIR}/libupb${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "protobuf::utf8_range=${LITERTLM_PROTOBUF_LIB_DIR}/libutf8_range${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "protobuf::utf8_validity=${LITERTLM_PROTOBUF_LIB_DIR}/libutf8_validity${CMAKE_STATIC_LIBRARY_SUFFIX}"
    CACHE INTERNAL "Mapping of protobuf targets"
)
