# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# ==============================================================================
# LiteRT-LM Abseil Target-to-Path Mapping
# ==============================================================================
set(LITERTLM_ABSL_TARGET_MAP
    "absl::base=${LITERTLM_ABSL_LIB_DIR}/libabsl_base.a"
    "absl::base_cpu_detect=${LITERTLM_ABSL_LIB_DIR}/libabsl_base_cpu_detect.a"
    "absl::city=${LITERTLM_ABSL_LIB_DIR}/libabsl_city.a"
    "absl::civil_time=${LITERTLM_ABSL_LIB_DIR}/libabsl_civil_time.a"
    "absl::clock_interface=${LITERTLM_ABSL_LIB_DIR}/libabsl_clock_interface.a"
    "absl::cord=${LITERTLM_ABSL_LIB_DIR}/libabsl_cord.a"
    "absl::cord_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_cord_internal.a"
    "absl::cordz_functions=${LITERTLM_ABSL_LIB_DIR}/libabsl_cordz_functions.a"
    "absl::cordz_handle=${LITERTLM_ABSL_LIB_DIR}/libabsl_cordz_handle.a"
    "absl::cordz_info=${LITERTLM_ABSL_LIB_DIR}/libabsl_cordz_info.a"
    "absl::cordz_sample_token=${LITERTLM_ABSL_LIB_DIR}/libabsl_cordz_sample_token.a"
    "absl::crc32c=${LITERTLM_ABSL_LIB_DIR}/libabsl_crc32c.a"
    "absl::crc_cord_state=${LITERTLM_ABSL_LIB_DIR}/libabsl_crc_cord_state.a"
    "absl::crc_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_crc_internal.a"
    "absl::debugging_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_debugging_internal.a"
    "absl::decode_rust_punycode=${LITERTLM_ABSL_LIB_DIR}/libabsl_decode_rust_punycode.a"
    "absl::demangle_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_demangle_internal.a"
    "absl::demangle_rust=${LITERTLM_ABSL_LIB_DIR}/libabsl_demangle_rust.a"
    "absl::die_if_null=${LITERTLM_ABSL_LIB_DIR}/libabsl_die_if_null.a"
    "absl::examine_stack=${LITERTLM_ABSL_LIB_DIR}/libabsl_examine_stack.a"
    "absl::exponential_biased=${LITERTLM_ABSL_LIB_DIR}/libabsl_exponential_biased.a"
    "absl::failure_signal_handler=${LITERTLM_ABSL_LIB_DIR}/libabsl_failure_signal_handler.a"
    "absl::flags_commandlineflag=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_commandlineflag.a"
    "absl::flags_commandlineflag_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_commandlineflag_internal.a"
    "absl::flags_config=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_config.a"
    "absl::flags_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_internal.a"
    "absl::flags_marshalling=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_marshalling.a"
    "absl::flags_parse=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_parse.a"
    "absl::flags_private_handle_accessor=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_private_handle_accessor.a"
    "absl::flags_program_name=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_program_name.a"
    "absl::flags_reflection=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_reflection.a"
    "absl::flags_usage=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_usage.a"
    "absl::flags_usage_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_flags_usage_internal.a"
    "absl::generic_printer_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_generic_printer_internal.a"
    "absl::graphcycles_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_graphcycles_internal.a"
    "absl::hardening=${LITERTLM_ABSL_LIB_DIR}/libabsl_hardening.a"
    "absl::hash=${LITERTLM_ABSL_LIB_DIR}/libabsl_hash.a"
    "absl::hashtable_profiler=${LITERTLM_ABSL_LIB_DIR}/libabsl_hashtable_profiler.a"
    "absl::hashtablez_sampler=${LITERTLM_ABSL_LIB_DIR}/libabsl_hashtablez_sampler.a"
    "absl::int128=${LITERTLM_ABSL_LIB_DIR}/libabsl_int128.a"
    "absl::kernel_timeout_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_kernel_timeout_internal.a"
    "absl::leak_check=${LITERTLM_ABSL_LIB_DIR}/libabsl_leak_check.a"
    "absl::log_entry=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_entry.a"
    "absl::log_flags=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_flags.a"
    "absl::log_globals=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_globals.a"
    "absl::log_initialize=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_initialize.a"
    "absl::log_internal_check_op=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_check_op.a"
    "absl::log_internal_conditions=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_conditions.a"
    "absl::log_internal_fnmatch=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_fnmatch.a"
    "absl::log_internal_format=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_format.a"
    "absl::log_internal_globals=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_globals.a"
    "absl::log_internal_log_sink_set=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_log_sink_set.a"
    "absl::log_internal_message=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_message.a"
    "absl::log_internal_nullguard=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_nullguard.a"
    "absl::log_internal_proto=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_proto.a"
    "absl::log_internal_structured_proto=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_internal_structured_proto.a"
    "absl::log_severity=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_severity.a"
    "absl::log_sink=${LITERTLM_ABSL_LIB_DIR}/libabsl_log_sink.a"
    "absl::malloc_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_malloc_internal.a"
    "absl::periodic_sampler=${LITERTLM_ABSL_LIB_DIR}/libabsl_periodic_sampler.a"
    "absl::poison=${LITERTLM_ABSL_LIB_DIR}/libabsl_poison.a"
    "absl::profile_builder=${LITERTLM_ABSL_LIB_DIR}/libabsl_profile_builder.a"
    "absl::random_distributions=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_distributions.a"
    "absl::random_internal_distribution_test_util=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_distribution_test_util.a"
    "absl::random_internal_entropy_pool=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_entropy_pool.a"
    "absl::random_internal_platform=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_platform.a"
    "absl::random_internal_randen=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_randen.a"
    "absl::random_internal_randen_hwaes=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_randen_hwaes.a"
    "absl::random_internal_randen_hwaes_impl=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_randen_hwaes_impl.a"
    "absl::random_internal_randen_slow=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_randen_slow.a"
    "absl::random_internal_seed_material=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_internal_seed_material.a"
    "absl::random_seed_gen_exception=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_seed_gen_exception.a"
    "absl::random_seed_sequences=${LITERTLM_ABSL_LIB_DIR}/libabsl_random_seed_sequences.a"
    "absl::raw_hash_set=${LITERTLM_ABSL_LIB_DIR}/libabsl_raw_hash_set.a"
    "absl::raw_logging_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_raw_logging_internal.a"
    "absl::scoped_set_env=${LITERTLM_ABSL_LIB_DIR}/libabsl_scoped_set_env.a"
    "absl::source_location=${LITERTLM_ABSL_LIB_DIR}/libabsl_source_location.a"
    "absl::spinlock_wait=${LITERTLM_ABSL_LIB_DIR}/libabsl_spinlock_wait.a"
    "absl::stacktrace=${LITERTLM_ABSL_LIB_DIR}/libabsl_stacktrace.a"
    "absl::status=${LITERTLM_ABSL_LIB_DIR}/libabsl_status.a"
    "absl::status_builder=${LITERTLM_ABSL_LIB_DIR}/libabsl_status_builder.a"
    "absl::statusor=${LITERTLM_ABSL_LIB_DIR}/libabsl_statusor.a"
    "absl::str_format_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_str_format_internal.a"
    "absl::strerror=${LITERTLM_ABSL_LIB_DIR}/libabsl_strerror.a"
    "absl::strings=${LITERTLM_ABSL_LIB_DIR}/libabsl_strings.a"
    "absl::strings_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_strings_internal.a"
    "absl::symbolize=${LITERTLM_ABSL_LIB_DIR}/libabsl_symbolize.a"
    "absl::synchronization=${LITERTLM_ABSL_LIB_DIR}/libabsl_synchronization.a"
    "absl::throw_delegate=${LITERTLM_ABSL_LIB_DIR}/libabsl_throw_delegate.a"
    "absl::time=${LITERTLM_ABSL_LIB_DIR}/libabsl_time.a"
    "absl::time_zone=${LITERTLM_ABSL_LIB_DIR}/libabsl_time_zone.a"
    "absl::tracing_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_tracing_internal.a"
    "absl::utf8_for_code_point=${LITERTLM_ABSL_LIB_DIR}/libabsl_utf8_for_code_point.a"
    "absl::vlog_config_internal=${LITERTLM_ABSL_LIB_DIR}/libabsl_vlog_config_internal.a"
    CACHE INTERNAL "Mapping of Abseil targets to their corresponding library paths"
)