# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# Expected inputs via -D: DEP_NAME, SEARCH_DIR, SEARCH_STR, OUTPUT_FILE

if(WIN32)
    set(_FILE_EXT ".lib")
elseif(APPLE)
    set(_FILE_EXT ".a")
else()
    set(_FILE_EXT ".a")
endif()
file(GLOB_RECURSE _FOUND_LIBS "${SEARCH_DIR}/*${_FILE_EXT}")

if(_FOUND_LIBS)
    list(REMOVE_DUPLICATES _FOUND_LIBS)
endif()

set(TARGET_MAP_LIST "")
foreach(_LIB_PATH IN LISTS _FOUND_LIBS)
    get_filename_component(_FILE_NAME "${_LIB_PATH}" NAME_WE)
    string(REGEX REPLACE "${SEARCH_DIR}" "" _LIB_RELPATH "${_LIB_PATH}")
    string(REGEX REPLACE "${_FILE_NAME}${_FILE_EXT}" "" _LIB_RELPATH "${_LIB_RELPATH}")
    string(REGEX REPLACE "^lib" "" _LIB_NAME "${_FILE_NAME}")
    list(APPEND TARGET_MAP_LIST "${DEP_NAME}::${_LIB_NAME}=\${${SEARCH_STR}}${_LIB_RELPATH}${_FILE_NAME}\${CMAKE_STATIC_LIBRARY_SUFFIX}")
endforeach()

string(TOUPPER "${DEP_NAME}" _DEP_UPPER)
set(_VAR_NAME "LITERTLM_${_DEP_UPPER}_TARGET_MAP")
set(_FILE_CONTENT "# --- Autogenerated target map for ${DEP_NAME}\n")
string(APPEND _FILE_CONTENT "# To preserve manual edits, set LITERTLM_GENERATE_TARGET_MAP=OFF\n\n")

string(APPEND _FILE_CONTENT "set(${_VAR_NAME}\n")
foreach(_MAP_ITEM IN LISTS TARGET_MAP_LIST)
    string(APPEND _FILE_CONTENT "    \"${_MAP_ITEM}\"\n")
endforeach()
string(APPEND _FILE_CONTENT "    CACHE INTERNAL \"Mapping of ${DEP_NAME} targets\"\n)\n")

if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _EXISTING_CONTENT)
    if(NOT _EXISTING_CONTENT STREQUAL _FILE_CONTENT)
        file(WRITE "${OUTPUT_FILE}" "${_FILE_CONTENT}")
        message(STATUS "[LiteRTLM] Build-time update: Target map for ${DEP_NAME}")
    endif()
else()
    file(WRITE "${OUTPUT_FILE}" "${_FILE_CONTENT}")
    message(STATUS "[LiteRTLM] Build-time create: Target map for ${DEP_NAME}")
endif()