# Copyright 2025 The ODML Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(
    default_hdrs_check = "strict",
    default_visibility = [
        "//:__subpackages__",
    ],
)

licenses(["notice"])

cc_library(
    name = "bitmap",
    hdrs = ["bitmap.h"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_absl//absl/base:core_headers"],
)

cc_library(
    name = "logit_mask",
    srcs = ["logit_mask.cc"],
    hdrs = ["logit_mask.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/types:span",
        "@litert//tflite/types:half",
    ],
)

cc_library(
    name = "constraint",
    srcs = ["constraint.cc"],
    hdrs = ["constraint.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":bitmap",
        ":logit_mask",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:status_macros",
        "@com_google_absl//absl/status:statusor",
    ],
)

cc_library(
    name = "external_constraint_config",
    hdrs = ["external_constraint_config.h"],
    deps = [
        ":constraint",
    ],
)

cc_library(
    name = "llg_constraint_config",
    hdrs = ["llg_constraint_config.h"],
)

cc_library(
    name = "fst_constraint_config",
    hdrs = ["fst_constraint_config.h"],
)

cc_library(
    name = "constraint_provider_config",
    hdrs = ["constraint_provider_config.h"],
    deps = [
        ":external_constraint_config",
        ":fst_constraint_config",
        ":llg_constraint_config",
    ],
)

cc_library(
    name = "constraint_provider",
    hdrs = ["constraint_provider.h"],
    deps = [
        ":constraint",
        ":constraint_provider_config",
        "@com_google_absl//absl/status:statusor",
    ],
)

cc_library(
    name = "no_repeat_ngram_config",
    hdrs = ["no_repeat_ngram_config.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "no_repeat_ngram_config_test",
    srcs = ["no_repeat_ngram_config_test.cc"],
    deps = [
        ":no_repeat_ngram_config",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "repetition_penalty_config",
    hdrs = ["repetition_penalty_config.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "repetition_penalty_config_test",
    srcs = ["repetition_penalty_config_test.cc"],
    deps = [
        ":repetition_penalty_config",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "suppress_tokens_config",
    hdrs = ["suppress_tokens_config.h"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_absl//absl/container:flat_hash_set"],
)

cc_test(
    name = "suppress_tokens_config_test",
    srcs = ["suppress_tokens_config_test.cc"],
    deps = [
        ":suppress_tokens_config",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "constrained_decoder",
    srcs = ["constrained_decoder.cc"],
    hdrs = ["constrained_decoder.h"],
    visibility = [
        "//:__subpackages__",
    ],
    deps = [
        ":constraint",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:status_macros",
        "@com_google_absl//absl/types:span",
        "@litert//litert/cc:litert_element_type",
        "@litert//litert/cc:litert_layout",
        "@litert//litert/cc:litert_macros",
        "@litert//litert/cc:litert_tensor_buffer",
        "@litert//litert/cc:litert_tensor_buffer_types",
        "//runtime/util:convert_tensor_buffer",
        "//runtime/util:litert_status_util",
        "@litert//tflite/types:half",
    ],
)

cc_library(
    name = "fake_constraint",
    srcs = ["fake_constraint.cc"],
    hdrs = ["fake_constraint.h"],
    deps = [
        ":bitmap",
        ":constraint",
        ":logit_mask",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
    ],
)

alias(
    name = "gemma_model_constraint_provider_lib",
    actual = ":gemma_model_constraint_provider_shared_lib",
)

cc_import(
    name = "gemma_model_constraint_provider_dll_import",
    interface_library = "//prebuilt/windows_x86_64:libGemmaModelConstraintProvider.lib",
    shared_library = "//prebuilt/windows_x86_64:libGemmaModelConstraintProvider.dll",
    target_compatible_with = ["@platforms//os:windows"],
)

cc_library(
    name = "gemma_model_constraint_provider_shared_lib",
    srcs = select({
        "//build_config:android_arm64": ["//prebuilt/android_arm64:libGemmaModelConstraintProvider.so"],
        "//build_config:android_x86_64": ["//prebuilt/android_x86_64:libGemmaModelConstraintProvider.so"],
        "//build_config:linux_x86_64": ["//prebuilt/linux_x86_64:libGemmaModelConstraintProvider.so"],
        "//build_config:linux_arm64": ["//prebuilt/linux_arm64:libGemmaModelConstraintProvider.so"],
        "//build_config:ios_sim_arm64": ["//prebuilt/ios_sim_arm64:libGemmaModelConstraintProvider.dylib"],
        "//build_config:ios_arm64": ["//prebuilt/ios_arm64:libGemmaModelConstraintProvider.dylib"],
        "@platforms//os:macos": ["//prebuilt/macos_arm64:libGemmaModelConstraintProvider.dylib"],
        "@platforms//os:windows": [],
        "//conditions:default": [],
    }),
    hdrs = [
        "gemma_model_constraint_provider.h",
    ],
    linkopts = select({
        "@platforms//os:ios": ["-Wl,-rpath,@loader_path"],
        "@platforms//os:macos": ["-Wl,-rpath,@loader_path"],
        "//conditions:default": [],
    }),
    linkstatic = 1,
    deps = [
        ":constraint",
        ":constraint_provider",
        ":constraint_provider_config",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@nlohmann_json//:json",
        "@sentencepiece//:sentencepiece_processor",
    ] + select({
        "@platforms//os:windows": [":gemma_model_constraint_provider_dll_import"],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "external_constraint_provider",
    srcs = ["external_constraint_provider.cc"],
    hdrs = ["external_constraint_provider.h"],
    deps = [
        ":constraint",
        ":constraint_provider",
        ":constraint_provider_config",
        ":external_constraint_config",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
    ],
)

cc_library(
    name = "llg_constraint",
    srcs = ["llg_constraint.cc"],
    hdrs = ["llg_constraint.h"],
    linkopts = select({
        "@platforms//os:windows": ["ntdll.lib"],
        "//conditions:default": [],
    }),
    deps = [
        ":bitmap",
        ":constraint",
        ":logit_mask",
        "@com_google_absl//absl/log:absl_log",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/types:span",
        "@crate_index__llguidance-1.3.0//:llguidance_cc"
    ] + select({
        "@platforms//os:windows": [
            "//rust:alloc_defs",
            "//rust:global_allocator",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "llg_constraint_provider",
    srcs = ["llg_constraint_provider.cc"],
    hdrs = ["llg_constraint_provider.h"],
    linkopts = select({
        "@platforms//os:windows": ["ntdll.lib"],
        "//conditions:default": [],
    }),
    deps = [
        ":constraint",
        ":constraint_provider",
        ":constraint_provider_config",
        ":llg_constraint",
        ":llg_constraint_config",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/container:flat_hash_set",
        "//support/tokenizer",
        "@crate_index__llguidance-1.3.0//:llguidance_cc"
    ] + select({
        "@platforms//os:windows": [
            "//rust:alloc_defs",
            "//rust:global_allocator",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "tool_utils",
    srcs = ["tool_utils.cc"],
    hdrs = ["tool_utils.h"],
    deps = [
        "@nlohmann_json//:json",
    ],
)

cc_test(
    name = "tool_utils_test",
    srcs = ["tool_utils_test.cc"],
    deps = [
        ":tool_utils",
        "@com_google_googletest//:gtest_main",
        "@nlohmann_json//:json",
    ],
)

cc_library(
    name = "llguidance_schema_utils",
    srcs = [
        "llg_fc_tool_calls.cc",
        "llg_python_tool_calls.cc",
        "llg_tool_call_utils.cc",
        "llguidance_schema_utils.cc",
    ],
    hdrs = [
        "llg_fc_tool_calls.h",
        "llg_python_tool_calls.h",
        "llg_tool_call_utils.h",
        "llguidance_schema_utils.h",
    ],
    deps = [
        ":tool_utils",
        "@com_google_absl//absl/functional:any_invocable",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@nlohmann_json//:json",
    ],
)

cc_test(
    name = "llguidance_schema_utils_test",
    srcs = ["llguidance_schema_utils_test.cc"],
    deps = [
        ":bitmap",
        ":constraint",
        ":llg_constraint_config",
        ":llg_constraint_provider",
        ":llguidance_schema_utils",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:status_macros",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/types:span",
        "@nlohmann_json//:json",
        "//runtime/util:litert_status_util",
        "//runtime/util:test_utils",
        "//support/tokenizer",
    ],
)

cc_test(
    name = "llg_tool_call_utils_test",
    srcs = ["llg_tool_call_utils_test.cc"],
    deps = [
        ":llguidance_schema_utils",
        "@com_google_googletest//:gtest_main",
        "@nlohmann_json//:json",
    ],
)

cc_test(
    name = "llg_python_tool_calls_test",
    srcs = ["llg_python_tool_calls_test.cc"],
    deps = [
        ":bitmap",
        ":constraint",
        ":llg_constraint_config",
        ":llg_constraint_provider",
        ":llguidance_schema_utils",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:status_macros",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/types:span",
        "@nlohmann_json//:json",
        "//runtime/util:litert_status_util",
        "//support/tokenizer",
    ],
)

cc_test(
    name = "llg_constraint_provider_test",
    srcs = ["llg_constraint_provider_test.cc"],
    deps = [
        ":llg_constraint_config",
        ":llg_constraint_provider",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/types:span",
        "//support/tokenizer",
        "//runtime/util:test_utils",
        "@crate_index__llguidance-1.3.0//:llguidance_cc"
    ],
)

cc_test(
    name = "llg_constraint_test",
    srcs = ["llg_constraint_test.cc"],
    deps = [
        ":bitmap",
        ":constraint",
        ":constraint_provider",
        ":llg_constraint_config",
        ":llg_constraint_provider",
        ":logit_mask",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/types:span",
        "//runtime/util:test_utils",
        "//support/tokenizer",
    ],
)

cc_test(
    name = "external_constraint_provider_test",
    srcs = ["external_constraint_provider_test.cc"],
    deps = [
        ":constraint",
        ":constraint_provider_config",
        ":external_constraint_config",
        ":external_constraint_provider",
        ":fake_constraint",
        ":fst_constraint_config",
        ":llg_constraint_config",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/status",
        "//runtime/util:test_utils",
    ],
)

cc_library(
    name = "constraint_provider_factory",
    srcs = ["constraint_provider_factory.cc"],
    hdrs = ["constraint_provider_factory.h"],
    deps = [
        ":constraint_provider",
        ":constraint_provider_config",
        ":external_constraint_config",
        ":external_constraint_provider",
        ":llg_constraint_config",
        ":llg_constraint_provider",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "//support/tokenizer",
    ],
)

cc_test(
    name = "constraint_provider_factory_test",
    srcs = ["constraint_provider_factory_test.cc"],
    deps = [
        ":constraint_provider_config",
        ":constraint_provider_factory",
        ":external_constraint_config",
        ":llg_constraint_config",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/types:span",
        "//runtime/util:test_utils",
        "//support/tokenizer",
    ],
)

cc_library(
    name = "thinking_budget_constraint",
    srcs = ["thinking_budget_constraint.cc"],
    hdrs = ["thinking_budget_constraint.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":bitmap",
        ":constraint",
        ":logit_mask",
        "@com_google_absl//absl/status:statusor",
        "//runtime/util:litert_status_util",
    ],
)

cc_test(
    name = "thinking_budget_constraint_test",
    srcs = ["thinking_budget_constraint_test.cc"],
    deps = [
        ":bitmap",
        ":fake_constraint",
        ":logit_mask",
        ":thinking_budget_constraint",
        "@com_google_googletest//:gtest_main",
        "//runtime/util:test_utils",
    ],
)

cc_test(
    name = "constraint_test",
    srcs = ["constraint_test.cc"],
    deps = [
        ":bitmap",
        ":constraint",
        ":logit_mask",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "//runtime/util:test_utils",
    ],
)

cc_test(
    name = "logit_mask_test",
    srcs = ["logit_mask_test.cc"],
    deps = [
        ":logit_mask",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/types:span",
        "//runtime/util:test_utils",
        "@litert//tflite/types:half",
    ],
)

cc_library(
    name = "suppress_tokens_constraint",
    srcs = ["suppress_tokens_constraint.cc"],
    hdrs = ["suppress_tokens_constraint.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":constraint",
        ":logit_mask",
        ":suppress_tokens_config",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/types:span",
    ],
)

cc_test(
    name = "suppress_tokens_constraint_test",
    srcs = ["suppress_tokens_constraint_test.cc"],
    deps = [
        ":logit_mask",
        ":suppress_tokens_config",
        ":suppress_tokens_constraint",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/types:span",
        "//runtime/util:test_utils",
        "@litert//tflite/types:half",
    ],
)

cc_library(
    name = "no_repeat_ngram_constraint",
    srcs = ["no_repeat_ngram_constraint.cc"],
    hdrs = ["no_repeat_ngram_constraint.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":constraint",
        ":logit_mask",
        ":no_repeat_ngram_config",
        "@com_google_absl//absl/container:fixed_array",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/hash",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/types:span",
    ],
)

cc_test(
    name = "no_repeat_ngram_constraint_test",
    srcs = ["no_repeat_ngram_constraint_test.cc"],
    deps = [
        ":logit_mask",
        ":no_repeat_ngram_config",
        ":no_repeat_ngram_constraint",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/types:span",
        "//runtime/util:test_utils",
        "@litert//tflite/types:half",
    ],
)

cc_library(
    name = "repetition_penalty_constraint",
    srcs = ["repetition_penalty_constraint.cc"],
    hdrs = ["repetition_penalty_constraint.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":constraint",
        ":logit_mask",
        ":repetition_penalty_config",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/types:span",
        "@litert//tflite/types:half",
    ],
)

cc_test(
    name = "repetition_penalty_constraint_test",
    srcs = ["repetition_penalty_constraint_test.cc"],
    deps = [
        ":logit_mask",
        ":repetition_penalty_config",
        ":repetition_penalty_constraint",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/types:span",
        "//runtime/util:test_utils",
        "@litert//tflite/types:half",
    ],
)

cc_library(
    name = "composite_constraint",
    srcs = ["composite_constraint.cc"],
    hdrs = ["composite_constraint.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":bitmap",
        ":constraint",
        ":logit_mask",
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:status_macros",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "composite_constraint_test",
    srcs = ["composite_constraint_test.cc"],
    deps = [
        ":bitmap",
        ":composite_constraint",
        ":constraint",
        ":constraint_provider",
        ":fake_constraint",
        ":llg_constraint_config",
        ":llg_constraint_provider",
        ":logit_mask",
        ":no_repeat_ngram_config",
        ":no_repeat_ngram_constraint",
        ":repetition_penalty_config",
        ":repetition_penalty_constraint",
        ":suppress_tokens_config",
        ":suppress_tokens_constraint",
        ":thinking_budget_constraint",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:string_view",
        "@com_google_absl//absl/types:span",
        "//runtime/util:test_utils",
        "//support/tokenizer",
        "@litert//tflite/types:half",
    ],
)
