# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include("${LITERTLM_MODULES_DIR}/utils.cmake")

include("${LITERTLM_LITERT_PACKAGE_DIR}/litert_config.cmake")
include("${LITERTLM_TFLITE_CONFIG_PATH}")
include("${LITERTLM_ABSL_CONFIG_PATH}")
include("${LITERTLM_PROTOBUF_CONFIG_PATH}")
include("${LITERTLM_FLATBUFFERS_CONFIG_PATH}")
include("${LITERTLM_SENTENCEPIECE_CONFIG_PATH}")

set(LITERTLM_LITERT_EXTERNAL_DONE ${LITERTLM_LITERT_STAMP_DIR}/litert_external-done CACHE INTERNAL "")
set(LITERTLM_LITERT_TAG "main" CACHE STRING "LiteRT git tag")

include(ExternalProject)
  if(TARGET fetch_content_complete)
    ExternalProject_Add(
      litert_external
      DEPENDS
        opencl_headers_external
        absl_external
        protobuf_external
        flatbuffers_external
        sentencepiece_external
        tokenizers-cpp_external
        tflite_external
        antlr_lib
        libpng_lib
        kissfft_lib
        miniaudio_lib
        minizip_lib
        minja_lib
        json_lib
        stb_impl
        zlib_lib

      GIT_REPOSITORY
        https://github.com/google-ai-edge/LiteRT.git
      GIT_TAG
        ${LITERTLM_LITERT_TAG}
      GIT_SUBMODULES ""
      GIT_SUBMODULES_RECURSE FALSE
      PREFIX
        ${LITERTLM_LITERT_EXT_PREFIX}
      SOURCE_SUBDIR
        litert
      BINARY_DIR
        ${LITERTLM_LITERT_BUILD_DIR}
      UPDATE_COMMAND
        git fetch origin ${LITERTLM_LITERT_TAG}
        COMMAND git reset --hard FETCH_HEAD
        COMMAND git clean -dfx
      PATCH_COMMAND
        ${CMAKE_COMMAND}
        "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
        "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
        "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
        "-DLITERTLM_LITERT_PACKAGE_DIR=${LITERTLM_LITERT_PACKAGE_DIR}"
        "-DLITERTLM_LITERT_CONFIG_PATH=${LITERTLM_LITERT_CONFIG_PATH}"
        "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
        "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
        "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
        "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
        "-DLITERTLM_FLATBUFFERS_PACKAGE_DIR=${LITERTLM_FLATBUFFERS_PACKAGE_DIR}"
        "-DLITERTLM_FLATBUFFERS_CONFIG_PATH=${LITERTLM_FLATBUFFERS_CONFIG_PATH}"
        "-DLITERTLM_SENTENCEPIECE_INCLUDE_PATHS=${LITERTLM_SENTENCEPIECE_INCLUDE_PATHS}"
        "-DLITERTLM_SENTENCEPIECE_CONFIG_PATH=${LITERTLM_SENTENCEPIECE_CONFIG_PATH}"
        "-DLITERTLM_TFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}"
        "-DLITERTLM_TFLITE_CONFIG_PATH=${LITERTLM_TFLITE_CONFIG_PATH}"
        "-DLITERTLM_TOKENIZERS_INSTALL_PREFIX=${LITERTLM_TOKENIZERS_INSTALL_PREFIX}/include"
        "-DLITERTLM_TOKENIZERS_SRC_DIR=${LITERTLM_TOKENIZERS_SRC_DIR}"
        "-DLITERTLM_TOKENIZERS_SRC_SUPPORT_DIR=${LITERTLM_TOKENIZERS_SRC_SUPPORT_DIR}"
        "-DLITERTLM_TOKENIZERS_SRC_INCLUDE_DIR=${LITERTLM_TOKENIZERS_SRC_INCLUDE_DIR}"
        "-DLITERTLM_TOKENIZERS_SRC_WEB_DIR=${LITERTLM_TOKENIZERS_SRC_WEB_DIR}"
        "-DLITERTLM_TOKENIZERS_INCLUDE_DIR=${LITERTLM_TOKENIZERS_INCLUDE_DIR}"
        "-DLITERTLM_STB_SRC_DIR=${LITERTLM_STB_SRC_DIR}"
        "-DCMAKE_INSTALL_LIBDIR=lib"
        "-DLITERTLM_OPENCL_INCLUDE_DIR=${LITERTLM_OPENCL_INCLUDE_DIR}"
        "-DLITERTLM_JSON_SRC_DIR=${LITERTLM_JSON_SRC_DIR}"
        "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
        "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"
        -DLITERTLM_KISSFFT_SRC_DIR=${LITERTLM_KISSFFT_SRC_DIR}
        -P "${LITERTLM_LITERT_PACKAGE_DIR}/litert_patcher.cmake"

    CMAKE_ARGS
        ${LITERTLM_TOOLCHAIN_FILE}
        ${LITERTLM_TOOLCHAIN_ARGS}
        ${LITERTLM_UV_ARGS}
        "-DCMAKE_GENERATOR=${CMAKE_GENERATOR}"
        "-DCMAKE_GENERATOR_PLATFORM=${CMAKE_GENERATOR_PLATFORM}"
        "-DLITERTLM_CMAKE_CROSSCOMPILING=${LITERTLM_CMAKE_CROSSCOMPILING}"
        "-DLITERTLM_LITERT_SHIM_PATH=${LITERTLM_LITERT_SHIM_PATH}"
        "-DLITERTLM_ORCHESTRATION_PHASE=${LITERTLM_ORCHESTRATION_PHASE}"
        "-DLITERTLM_BIN_EXT=${LITERTLM_BIN_EXT}"
        "-DLITERTLM_STATIC_LIB_EXT=${LITERTLM_STATIC_LIB_EXT}"
        "-DLITERTLM_DYN_LIB_EXT=${LITERTLM_DYN_LIB_EXT}"
        "-DLITERTLM_LIB_PREFIX=${LITERTLM_LIB_PREFIX}"
        "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
        "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
        "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
        "-DLITERTLM_LITERT_PACKAGE_DIR=${LITERTLM_LITERT_PACKAGE_DIR}"
        "-DLITERTLM_LITERT_CONFIG_PATH=${LITERTLM_LITERT_CONFIG_PATH}"
        "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
        "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
        "-DLITERTLM_ABSL_AGGREGATE_PATH=${LITERTLM_ABSL_AGGREGATE_PATH}"
        "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
        "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
        "-DLITERTLM_PROTOBUF_AGGREGATE_PATH=${LITERTLM_PROTOBUF_AGGREGATE_PATH}"
        "-DLITERTLM_FLATBUFFERS_PACKAGE_DIR=${LITERTLM_FLATBUFFERS_PACKAGE_DIR}"
        "-DLITERTLM_FLATBUFFERS_CONFIG_PATH=${LITERTLM_FLATBUFFERS_CONFIG_PATH}"
        "-DLITERTLM_FLATBUFFERS_AGGREGATE_PATH=${LITERTLM_FLATBUFFERS_AGGREGATE_PATH}"
        "-DLITERTLM_SENTENCEPIECE_PACKAGE_DIR=${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}"
        "-DLITERTLM_SENTENCEPIECE_CONFIG_PATH=${LITERTLM_SENTENCEPIECE_CONFIG_PATH}"
        "-DLITERTLM_SENTENCEPIECE_AGGREGATE_PATH=${LITERTLM_SENTENCEPIECE_AGGREGATE_PATH}"
        "-DLITERTLM_TFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}"
        "-DLITERTLM_TFLITE_CONFIG_PATH=${LITERTLM_TFLITE_CONFIG_PATH}"
        "-DLITERTLM_TFLITE_AGGREGATE_PATH=${LITERTLM_TFLITE_AGGREGATE_PATH}"
        "-DLITERTLM_TFLITE_BUILD_DIR=${LITERTLM_TFLITE_BUILD_DIR}"

        "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
        "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5
        -DCMAKE_POLICY_DEFAULT_CMP0169=OLD
        -DCMAKE_POLICY_DEFAULT_CMP0170=OLD
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
        -DCMAKE_CXX_STANDARD_REQUIRED=ON
        -DCMAKE_CXX_EXTENSIONS=OFF
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        "-DCMAKE_PREFIX_PATH=${LITERTLM_ABSL_INSTALL_PREFIX}; ${LITERTLM_TFLITE_INSTALL_PREFIX}; ${LITERTLM_PROTOBUF_INSTALL_PREFIX}; ${LITERTLM_FLATBUFFERS_INSTALL_PREFIX}"
        "-DCMAKE_CXX_FLAGS:STRING= ${LITERTLM_LITERT_CXX_FLAGS_Construct} -isystem ${LITERTLM_TFLITE_INSTALL_PREFIX}/include -isystem ${LITERTLM_ABSL_INSTALL_PREFIX}/include -isystem ${PROTOBUF_INSTALL_PREFIX}/include -w"
        "-DCMAKE_C_FLAGS:STRING= ${CMAKE_C_FLAGS} -isystem ${LITERTLM_TFLITE_INSTALL_PREFIX}/include"

        -DCL_TARGET_OPENCL_VERSION=220
        -DCL_HPP_TARGET_OPENCL_VERSION=220
        -DCL_HPP_MIN_TARGET_OPENCL_VERSION=220

        "-D_abseil-cpp_LICENSE_FILE:FILEPATH=${LITERTLM_ABSL_EXT_PREFIX}/src/absl_external/LICENSE"
        "-DFETCHCONTENT_SOURCE_DIR_ABSEIL-CPP=${LITERTLM_ABSL_EXT_PREFIX}/src/absl_external"
        -DLITERTLM_absl_SOURCE_DIR=${LITERTLM_ABSL_SRC_DIR}
        -DLITERTLM_absl_BINARY_DIR=${LITERTLM_ABSL_BUILD_DIR}
        -DLITERTLM_absl_INCLUDE_DIR=${LITERTLM_ABSL_INCLUDE_DIR}
        -DLITERTLM_ABSL_INCLUDE_DIR=${LITERTLM_ABSL_INCLUDE_DIR}
        -DLITERTLM_ABSL_LIBRARIES=${LITERTLM_ABSL_LIBS_DIR}
        -DLITERTLM_absl_DIR=${LITERTLM_ABSL_LIBS_DIR}

        -DFLATBUFFERS_BUILD_FLATC=OFF
        -DFLATBUFFERS_INSTALL=OFF
        -DFLATBUFFERS_PROJECT_DIR=${LITERTLM_FLATBUFFERS_SRC_DIR}/flatbuffers_external
        -DFlatBuffers_BINARY_DIR=${LITERTLM_FLATBUFFERS_BIN_DIR}
        -DFlatBuffers_SOURCE_DIR=${LITERTLM_FLATBUFFERS_SRC_DIR}/flatbuffers_external
        -D_flatbuffers_LICENSE_FILE:FILEPATH=${LITERTLM_FLATBUFFERS_SRC_DIR}/flatbuffers_external/LICENSE
        -DFLATC_PATHS=${LITERTLM_FLATBUFFERS_BIN_DIR}
        -DFLATBUFFERS_FLATC_EXECUTABLE=${LITERTLM_FLATC_EXECUTABLE}
        -DFLATC_EXECUTABLE=${LITERTLM_FLATC_EXECUTABLE}
        -Dflatbuffers_DIR=${LITERTLM_FLATBUFFERS_INSTALL_PREFIX}/lib/cmake/flatbuffers
        -DFETCHCONTENT_SOURCE_DIR_FLATBUFFERS=${LITERTLM_FLATBUFFERS_SRC_DIR}/flatbuffers_external
        -DFLATBUFFERS_INSTALL_PREFIX=${LITERTLM_FLATBUFFERS_INSTALL_PREFIX}
        -DFLATBUFFERS_LIB_DIR=${LITERTLM_FLATBUFFERS_LIB_DIR}
        -DFLATBUFFERS_INCLUDE_DIR=${LITERTLM_FLATBUFFERS_INCLUDE_DIR}
        -DFLATC_EXECUTABLE=${LITERTLM_FLATC_EXECUTABLE}

        -DTFLite_DIR=${LITERTLM_TFLITE_INSTALL_PREFIX}/lib
        -Dtensorflow-lite_DIR=${LITERTLM_TFLITE_INSTALL_PREFIX}/lib
        -DTFLITE_SOURCE_DIR=${LITERTLM_TFLITE_SRC_DIR}
        -DTENSORFLOW_SOURCE_DIR=${TENSORFLOW_SOURCE_DIR}

        -DLITERT_AUTO_BUILD_TFLITE=OFF
        -DTFLITE_ENABLE_INSTALL=OFF
        -DTFLITE_ENABLE_XNNPACK=ON
        -DTFLITE_ENABLE_RESOURCE_VARIABLE=OFF
        -DXNNPACK_SET_VERBOSITY=OFF
        -DTFLITE_ENABLE_GPU=OFF
        -DLITERT_ENABLE_GPU=OFF
        -DLITERT_ENABLE_NPU=ON
        -DLITERT_ENABLE_QUALCOMM=ON
        -DLITERT_DISABLE_KLEIDIAI=ON
        -DLITERT_BUILD_C_API=ON
        -DLITERT_BUILD_TOOLS=OFF

        -DLITERTLM_TFLITE_SRC_DIR=${LITERTLM_TFLITE_SRC_DIR}
        -DLITERTLM_TFLITE_PACKAGE_DIR=${LITERTLM_TFLITE_PACKAGE_DIR}
        -DLITERTLM_TENSORFLOW_SOURCE_DIR=${LITERTLM_TENSORFLOW_SOURCE_DIR}
        -DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}
        -DLITERTLM_LITERT_SRC_DIR=${LITERTLM_LITERT_SRC_DIR}
        -DLITERTLM_ABSL_LIBS_FLAT=${LITERTLM_ABSL_LIBS_FLAT}
        -DLITERTLM_ABSL_LIB_DIR=${LITERTLM_ABSL_LIB_DIR}
        -DLITERTLM_ABSL_INCLUDE_DIR=${LITERTLM_ABSL_INCLUDE_DIR}
        -DLITERTLM_OPENCL_INCLUDE_DIR=${LITERTLM_OPENCL_INCLUDE_DIR}
        -DLITERTLM_JSON_SRC_DIR=${LITERTLM_JSON_SRC_DIR}
        "-DLITERTLM_TFLITE_BUILD_DIR=${LITERTLM_TFLITE_BUILD_DIR}"

        -DTFLITE_FORCE_LOAD_TARGETS=${LITERTLM_TFLITE_FORCE_LOAD_TARGETS}
        -DTFLITE_STANDARD_TARGETS=${LITERTLM_TFLITE_STANDARD_TARGETS}
        -DTFLITE_INCLUDE_DIR=${LITERTLM_TFLITE_INCLUDE_DIR}
        -DTFLITE_BUILD_DIR=${LITERTLM_TFLITE_BUILD_DIR}
        -DTFLITE_LIB_DIR=${LITERTLM_TFLITE_LIB_DIR}
        -DPROTO_LIB_DIR=${LITERTLM_PROTOBUF_LIB_DIR}
        -DXNNPACK_SOURCE_DIR=${LITERTLM_XNNPACK_SOURCE_DIR}
        -DXNNPACK_BINARY_DIR=${LITERTLM_XNNPACK_BINARY_DIR}
        -DXNNPACK_INCLUDE_DIR=${LITERTLM_XNNPACK_INCLUDE_DIR}
        -DXNNPACK_LIB_DIR=${LITERTLM_XNNPACK_LIB_DIR}
        -DPROTO_PROTOC_EXECUTABLE=${LITERTLM_PROTOC_EXECUTABLE}
        "-DLITERTLM_TOKENIZERS_INSTALL_PREFIX=${LITERTLM_TOKENIZERS_INSTALL_PREFIX}"
        "-DLITERTLM_TOKENIZERS_SRC_DIR=${LITERTLM_TOKENIZERS_SRC_DIR}"
        "-DLITERTLM_TOKENIZERS_SRC_INCLUDE_DIR=${LITERTLM_TOKENIZERS_SRC_INCLUDE_DIR}"
        "-DLITERTLM_TOKENIZERS_INCLUDE_DIR=${LITERTLM_TOKENIZERS_INCLUDE_DIR}"
        "-DLITERTLM_TOKENIZERS_SRC_SENTENCEPIECE_DIR=${LITERTLM_TOKENIZERS_SRC_SENTENCEPIECE_DIR}"
        "-DLITERTLM_TOKENIZERS_PACKAGE_DIR=${LITERTLM_TOKENIZERS_PACKAGE_DIR}"

        "-DLITERTLM_STB_SRC_DIR=${LITERTLM_STB_SRC_DIR}"
        -DLITERTLM_KISSFFT_SRC_DIR=${LITERTLM_KISSFFT_SRC_DIR}
        -DLITERTLM_MINIAUDIO_SRC_DIR=${LITERTLM_MINIAUDIO_SRC_DIR}
        -DLITERTLM_MINIZIP_SRC_DIR=${LITERTLM_MINIZIP_SRC_DIR}/minizip
        -DLITERTLM_MINJA_SRC_DIR=${LITERTLM_MINJA_SRC_DIR}/include
        -DLITERTLM_FETCHCONTENT_MODULE_INCLUDE_DIR=${LITERTLM_FETCHCONTENT_MODULE_INCLUDE_DIR}
        -DLITERTLM_FETCHCONTENT_MODULE_SRC_DIRS=${LITERTLM_FETCHCONTENT_MODULE_SRC_DIRS}

      INSTALL_COMMAND ""
    )
    if(LITERTLM_GENERATE_TARGET_MAP)
      ExternalProject_Add_Step(litert_external generate_target_map
        COMMAND ${CMAKE_COMMAND}
            "-DDEP_NAME=litert"
            "-DSEARCH_DIR=${LITERTLM_LITERT_BUILD_DIR}"
            "-DSEARCH_STR=LITERTLM_LITERT_BUILD_DIR"
            "-DOUTPUT_FILE=${LITERTLM_LITERT_TARGET_MAP_PATH}"
            -P ${LITERTLM_SCRIPTS_DIR}/generate_target_map.cmake
        DEPENDEES install
        BYPRODUCTS ${LITERTLM_LITERT_TARGET_MAP_PATH}
      )
    endif()
else()
  message(FATAL_ERROR "fetch_content_complete does not exist")
endif()

message(STATUS "[LiteRTLM] LiteRT already installed at: ${LITERTLM_LITERT_INSTALL_PREFIX}")
if(NOT TARGET litert_external)
    add_custom_target(litert_external)
endif()

include(${LITERTLM_LITERT_AGGREGATE_PATH})
generate_litert_aggregate()
