// Copyright 2026 The ODML Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package litert.lm.proto;

import "runtime/proto/asr_model_type.proto";

option java_multiple_files = true;
option java_outer_classname = "AsrMetadataOuterClass";

// Parameters for Automatic Speech Recognition (ASR) models.
message AsrMetadata {
  enum TfLiteModelType {
    // Placeholder for unspecified model type.
    TF_LITE_MODEL_TYPE_UNSPECIFIED = 0;
    // The tflite model with both encoder and decoder in a single graph.
    TF_LITE_ENCODER_DECODER = 1;
    // The tflite model for the audio encoder.
    TF_LITE_AUDIO_ENCODER = 2;
    // The tflite model for the text decoder.
    TF_LITE_TEXT_DECODER = 3;
  }

  // ASR model type.
  AsrModelType asr_model_type = 1;
}
