# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set(absl_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/lib/cmake/absl" CACHE INTERNAL "")
set(_abseil-cpp_LICENSE_FILE "${ABSL_SRC_DIR}/absl_external/LICENSE" CACHE INTERNAL "")
set(ABSL_INCLUDE_DIR "${LITERTLM_ABSL_INCLUDE_DIR}" CACHE INTERNAL "")
set(ABSL_PACKAGE_DIR "${ABSL_PACKAGE_DIR}" CACHE INTERNAL "")

set(PROTOBUF_PACKAGE_DIR "${LITERTLM_PROTOBUF_PACKAGE_DIR}" CACHE INTERNAL "")
set(PROTO_PROTOC_EXECUTABLE "${LITERTLM_PROTOBUF_PROTOC_EXECUTABLE}" CACHE INTERNAL "")
set(PROTOBUF_INCLUDE_DIR "${LITERTLM_PROTOBUF_INCLUDE_DIR}" CACHE INTERNAL "")
set(protobuf_BINARY_DIR "${LITERTLM_PROTOBUF_BIN_DIR}" CACHE INTERNAL "")
set(protobuf_BUILD_PROTOC_BINARIES OFF CACHE INTERNAL "")
set(protobuf_SOURCE_DIR "${LITERTLM_PROTOBUF_SRC_DIR}" CACHE INTERNAL "")
set(PROTO_INSTALL_PREFIX "${LITERTLM_PROTOBUF_INSTALL_PREFIX}" CACHE INTERNAL "")
set(PROTO_SRC_DIR "${LITERTLM_PROTOBUF_SRC_DIR}" CACHE INTERNAL "")
set(PROTO_INCLUDE_DIR "${LITERTLM_PROTOBUF_INCLUDE_DIR}" CACHE INTERNAL "")
set(PROTO_LIB_DIR "${LITERTLM_PROTOBUF_LIB_DIR}" CACHE INTERNAL "")

set(FLATBUFFERS_INCLUDE_DIR "${LITERTLM_FLATBUFFERS_INCLUDE_DIR}" CACHE INTERNAL "")
set(FLATBUFFERS_BUILD_FLATC OFF CACHE INTERNAL "")
set(FLATBUFFERS_INSTALL OFF CACHE INTERNAL "")
set(FlatBuffers_BINARY_DIR "${LITERTLM_FLATBUFFERS_BIN_DIR}" CACHE INTERNAL "")
set(FLATBUFFERS_PROJECT_DIR "${LITERTLM_FLATBUFFERS_SRC_DIR}/flatbuffers_external" CACHE INTERNAL "")
set(FlatBuffers_SOURCE_DIR "${LITERTLM_FLATBUFFERS_SRC_DIR}/flatbuffers_external" CACHE INTERNAL "")
set(_flatbuffers_LICENSE_FILE "${LITERTLM_FLATBUFFERS_SRC_DIR}/flatbuffers_external/LICENSE" CACHE INTERNAL "")
set(FLATC_PATHS "${LITERTLM_FLATBUFFERS_BIN_DIR}" CACHE INTERNAL "")
set(FLATBUFFERS_FLATC_EXECUTABLE "${FLATC_EXECUTABLE}" CACHE INTERNAL "")
set(flatbuffers_DIR "${LITERTLM_FLATBUFFERS_INSTALL_PREFIX}/lib/cmake/flatbuffers" CACHE INTERNAL "")
set(FLATC_TARGET "${FLATC_EXECUTABLE}" CACHE INTERNAL "")
set(FLATC_EXECUTABLE "${FLATC_EXECUTABLE}" CACHE INTERNAL "")
set(FLATBUFFERS_PACKAGE_DIR "${LITERTLM_FLATBUFFERS_PACKAGE_DIR}" CACHE INTERNAL "")