# --- Autogenerated target map for flatbuffers
# To preserve manual edits, set LITERTLM_GENERATE_TARGET_MAP=OFF

set(LITERTLM_FLATBUFFERS_TARGET_MAP
    "flatbuffers::flatbuffers=${LITERTLM_FLATBUFFERS_LIB_DIR}/libflatbuffers${CMAKE_STATIC_LIBRARY_SUFFIX}"
    CACHE INTERNAL "Mapping of flatbuffers targets"
)
